# Generated by Django 3.1.2 on 2020-10-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
