# Generated by Django 3.1.2 on 2020-10-28 03:45

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(validators=[item.models.validate_positive])),
                ('description', models.CharField(max_length=200)),
                ('availibility', models.IntegerField(validators=[item.models.validate_positive])),
                ('availibility_status', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(validators=[item.models.validate_positive])),
                ('availibility', models.IntegerField(validators=[item.models.validate_positive])),
                ('availibility_status', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('Indian', 'Indian'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('North Indian', 'South Indian')], default='North Indian', max_length=100)),
                ('photo', models.ImageField(upload_to='gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
