# Generated by Django 3.1.2 on 2020-10-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='availibility_status',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='availibility_status',
            new_name='is_available',
        ),
    ]
