# Generated by Django 3.1.2 on 2020-10-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20201028_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('South Indian', 'South Indian'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese'), ('North Indian', 'North Indian')], default='North Indian', max_length=100),
        ),
    ]
