# Generated by Django 3.1.2 on 2020-10-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20201028_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='availibility',
        ),
        migrations.RemoveField(
            model_name='item',
            name='availibility',
        ),
    ]
