# Generated by Django 3.1.2 on 2020-10-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20201028_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='photo',
        ),
    ]
